### ISSUE TITLE
Cargar modelos 3D

### ISSUE THREAD

**Issue by Darumosso** [keros-prp/orrery-space-apps#2]

**Comment by Darumosso** [comment]
"Solar System" (https://skfb.ly/6ryJH) by valmirt is licensed under Creative Commons Attribution (http://creativecommons.org/licenses/by/4.0/).

# Posibles créditos para el modelo

**Comment by Morall0** [comment]
Para cargar un modelo en 3d se necesita poner el modelo en /static/models/, es decir, el archivo gltf, .bin y las texutras necesarias, una vez hecho eso, se corre el comando `npm run model-pipeline:run`, lo que genera un componente de Svelte con el modelo automáticamente en la carpeta /src/lib/components/models.

**Comment by Morall0** [comment]
Posibles créditos para el SkyBox: ESO/S. Brunier !(https://www.eso.org/public/images/eso0932a/)[Image Link]
